emit:
  - "@typespec/openapi3"
  - "@microsoft/typespec-copilot-skills"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/.generated/openapi"
    file-type: json 
  "@microsoft/typespec-copilot-skills":
    emitter-output-dir: "{project-root}/.generated/declarative-agent"
    file-type: json
    output-file: "agent-manifest"
